// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ORMapperSample.Data;

#nullable disable

namespace ORMapperSample.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250719064115_AddCategoryTable")]
    partial class AddCategoryTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("ORMapperSample.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "電子機器"
                        },
                        new
                        {
                            Id = 2,
                            Name = "書籍"
                        },
                        new
                        {
                            Id = 3,
                            Name = "日用品"
                        });
                });

            modelBuilder.Entity("ORMapperSample.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 7, 19, 15, 41, 14, 568, DateTimeKind.Local).AddTicks(1598),
                            Description = "これはサンプル商品1の説明です",
                            Name = "サンプル商品1",
                            Price = 1000m,
                            Quantity = 10,
                            UpdatedAt = new DateTime(2025, 7, 19, 15, 41, 14, 568, DateTimeKind.Local).AddTicks(1615)
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 7, 19, 15, 41, 14, 568, DateTimeKind.Local).AddTicks(1618),
                            Description = "これはサンプル商品2の説明です",
                            Name = "サンプル商品2",
                            Price = 2000m,
                            Quantity = 5,
                            UpdatedAt = new DateTime(2025, 7, 19, 15, 41, 14, 568, DateTimeKind.Local).AddTicks(1619)
                        });
                });

            modelBuilder.Entity("ORMapperSample.Models.Product", b =>
                {
                    b.HasOne("ORMapperSample.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ORMapperSample.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
