// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ORMapperSample.Data;

#nullable disable

namespace ORMapperSample.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250719023919_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("ORMapperSample.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 7, 19, 11, 39, 19, 537, DateTimeKind.Local).AddTicks(823),
                            Description = "これはサンプル商品1の説明です",
                            Name = "サンプル商品1",
                            Price = 1000m,
                            Quantity = 10,
                            UpdatedAt = new DateTime(2025, 7, 19, 11, 39, 19, 537, DateTimeKind.Local).AddTicks(839)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 7, 19, 11, 39, 19, 537, DateTimeKind.Local).AddTicks(842),
                            Description = "これはサンプル商品2の説明です",
                            Name = "サンプル商品2",
                            Price = 2000m,
                            Quantity = 5,
                            UpdatedAt = new DateTime(2025, 7, 19, 11, 39, 19, 537, DateTimeKind.Local).AddTicks(843)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
